#define BIT(x) 			(1 << (x))
#define SETBITS(x,y) 	((x) |= (y))
#define CLEARBITS(x,y) 	((x) &= (~(y)))
#define SETBIT(x,y) 	SETBITS((x), (BIT((y))))			/* EXAMPLE SETBIT(PORTB,2) sets the 2 bit of PORTB */
#define CLRBIT(x,y) 	CLEARBITS((x), (BIT((y))))
#define BITSET(x,y) 	((x) & (BIT(y)))
#define BITCLEAR(x,y) 	!BITSET((x), (y))
#define BITSSET(x,y) 	(((x) & (y)) == (y))
#define BITSCLEAR(x,y) 	(((x) & (y)) == 0)
#define TSTBIT(x,y) 	(((x)>>(y)) & 1)
#define TGLBIT(x,y)     (TSTBIT(x,y))?CLEARBITS(x,y):SETBIT(x,y)
//Outputs
#define DIR1         TSTBIT(PORTK.OUT,4) //hello
#define SET_DIR1     SETBIT(PORTK.OUT,4)
#define CLR_DIR1     CLRBIT(PORTK.OUT,4)
#define PULSE1       PORTK.OUTTGL = 0x20 //TGLBIT(PORTK.OUT,5)
#define EMG1         TSTBIT(PORTA.OUT,6)
#define SET_EMG1     SETBIT(PORTA.OUT,6)
#define CLR_EMG1     CLRBIT(PORTA.OUT,6)
#define ENABLE1      TSTBIT(PORTA.OUT,7)
#define SET_ENABLE1  SETBIT(PORTA.OUT,7)
#define CLR_ENABLE1  CLRBIT(PORTA.OUT,7)

#define DIR2         TSTBIT(PORTK.OUT,2)
#define SET_DIR2     SETBIT(PORTK.OUT,2)
#define CLR_DIR2     CLRBIT(PORTK.OUT,2)
#define PULSE2       PORTK.OUTTGL=0x08//TGLBIT(PORTK.OUT,3)
#define EMG2         TSTBIT(PORTB.OUT,4)
#define SET_EMG2     SETBIT(PORTB.OUT,4)
#define CLR_EMG2     CLRBIT(PORTB.OUT,4)
#define ENABLE2      TSTBIT(PORTB.OUT,7)
#define SET_ENABLE2  SETBIT(PORTB.OUT,7)
#define CLR_ENABLE2  CLRBIT(PORTB.OUT,7)

#define DIR3         TSTBIT(PORTK.OUT,0)
#define SET_DIR3     SETBIT(PORTK.OUT,0)
#define CLR_DIR3     CLRBIT(PORTK.OUT,0)
#define PULSE3       PORTK.OUTTGL=0x02//TGLBIT(PORTK.OUT,1)
//#define EMG3         TSTBIT(PORTC.OUT,3)
//#define SET_EMG3     SETBIT(PORTC.OUT,3)
//#define CLR_EMG3     CLRBIT(PORTC.OUT,3)
#define ENABLE3      TSTBIT(PORTC.OUT,7)
#define SET_ENABLE3  SETBIT(PORTC.OUT,7)
#define CLR_ENABLE3  CLRBIT(PORTC.OUT,7)

#define DO1_SET      SETBIT(PORTJ.OUT,2)
#define DO1_CLR      CLRBIT(PORTJ.OUT,2)
#define DO2_SET      SETBIT(PORTJ.OUT,3)
#define DO2_CLR      CLRBIT(PORTJ.OUT,3)
#define DO3_SET      SETBIT(PORTJ.OUT,4)
#define DO3_CLR      CLRBIT(PORTJ.OUT,4)
#define DO4_SET      SETBIT(PORTJ.OUT,5)
#define DO4_CLR      CLRBIT(PORTJ.OUT,5)
#define DO5_SET      SETBIT(PORTJ.OUT,7)
#define DO5_CLR      CLRBIT(PORTJ.OUT,7)
#define DO6_SET      SETBIT(PORTJ.OUT,6)
#define DO6_CLR      CLRBIT(PORTJ.OUT,6)

#define SG11_SET     SETBIT(PORTH.OUT,3) 
#define SG11_CLR     CLRBIT(PORTH.OUT,3) 
#define SG12_SET     SETBIT(PORTH.OUT,2) 
#define SG12_CLR     CLRBIT(PORTH.OUT,2) 
#define SG13_SET     SETBIT(PORTH.OUT,5) 
#define SG13_CLR     CLRBIT(PORTH.OUT,5) 
#define SG14_SET     SETBIT(PORTH.OUT,4) 
#define SG14_CLR     CLRBIT(PORTH.OUT,4) 
#define SG15_SET     SETBIT(PORTH.OUT,7) 
#define SG15_CLR     CLRBIT(PORTH.OUT,7) 
#define SG16_SET     SETBIT(PORTH.OUT,6) 
#define SG16_CLR     CLRBIT(PORTH.OUT,6) 
#define SG17_SET     SETBIT(PORTJ.OUT,1) 
#define SG17_CLR     CLRBIT(PORTJ.OUT,1) 
#define SG18_SET     SETBIT(PORTJ.OUT,0) 
#define SG18_CLR     CLRBIT(PORTJ.OUT,0)  

#define LED1         PORTR.OUTTGL=0x01//TGLBIT(PORTR.OUT,0)
#define LED2         PORTR.OUTTGL=0x02//TGLBIT(PORTR.OUT,1)

#define SETSFRST     SETBIT(PORTE.OUT,2)
#define CLRSFRST     CLRBIT(PORTE.OUT,2)

#define SETSFWP      SETBIT(PORTE.OUT,1)
#define CLRSFWP      CLRBIT(PORTE.OUT,1)

#define SetDataReady SETBIT(PORTF.OUT,0)
#define ClrDataReady CLRBIT(PORTF.OUT,0)
/****************************************************/    
/*****Inputs*****************************************/
#define READY1       TSTBIT(PORTA.IN,0)
#define INPOS1       TSTBIT(PORTA.IN,1)
#define ALARM1       TSTBIT(PORTA.IN,2)
#define LIM_POS1     TSTBIT(PORTA.IN,3)
#define LIM_NEG1     TSTBIT(PORTA.IN,4)
#define REF1         TSTBIT(PORTA.IN,5)

#define READY2       TSTBIT(PORTB.IN,3)
#define INPOS2       TSTBIT(PORTB.IN,2)
#define ALARM2       TSTBIT(PORTB.IN,1)
#define LIM_POS2     TSTBIT(PORTB.IN,0)
#define LIM_NEG2     TSTBIT(PORTB.IN,6)
#define REF2         TSTBIT(PORTB.IN,5)

#define READY3       TSTBIT(PORTC.IN,2)
#define INPOS3       TSTBIT(PORTC.IN,1)
#define ALARM3       TSTBIT(PORTC.IN,0)
#define LIM_POS3     TSTBIT(PORTC.IN,5)
#define LIM_NEG3     TSTBIT(PORTC.IN,4)
#define REF3         TSTBIT(PORTC.IN,6)

#define JogPos       TSTBIT(PORTH.IN,1)
#define JogNeg       TSTBIT(PORTD.IN,3)

#define RunProgram   TSTBIT(PORTD.IN,1)

#define StopProgram  TSTBIT(PORTD.IN,2)

